package com.yugyg.entity;

import java.util.Date;

public class YgfCalendar {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygf_calendar.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygf_calendar.num
     *
     * @mbg.generated
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygf_calendar.date
     *
     * @mbg.generated
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygf_calendar.id
     *
     * @return the value of ygf_calendar.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygf_calendar.id
     *
     * @param id the value for ygf_calendar.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygf_calendar.num
     *
     * @return the value of ygf_calendar.num
     *
     * @mbg.generated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygf_calendar.num
     *
     * @param num the value for ygf_calendar.num
     *
     * @mbg.generated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygf_calendar.date
     *
     * @return the value of ygf_calendar.date
     *
     * @mbg.generated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygf_calendar.date
     *
     * @param date the value for ygf_calendar.date
     *
     * @mbg.generated
     */
    public void setDate(Date date) {
        this.date = date;
    }
}