package com.yugyg.entity;

public class YgfCity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygf_city.city_id
     *
     * @mbg.generated
     */
    private Long cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygf_city.city_code
     *
     * @mbg.generated
     */
    private String cityCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygf_city.province_id
     *
     * @mbg.generated
     */
    private Long provinceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygf_city.city_name
     *
     * @mbg.generated
     */
    private String cityName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygf_city.city_id
     *
     * @return the value of ygf_city.city_id
     *
     * @mbg.generated
     */
    public Long getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygf_city.city_id
     *
     * @param cityId the value for ygf_city.city_id
     *
     * @mbg.generated
     */
    public void setCityId(Long cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygf_city.city_code
     *
     * @return the value of ygf_city.city_code
     *
     * @mbg.generated
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygf_city.city_code
     *
     * @param cityCode the value for ygf_city.city_code
     *
     * @mbg.generated
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygf_city.province_id
     *
     * @return the value of ygf_city.province_id
     *
     * @mbg.generated
     */
    public Long getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygf_city.province_id
     *
     * @param provinceId the value for ygf_city.province_id
     *
     * @mbg.generated
     */
    public void setProvinceId(Long provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygf_city.city_name
     *
     * @return the value of ygf_city.city_name
     *
     * @mbg.generated
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygf_city.city_name
     *
     * @param cityName the value for ygf_city.city_name
     *
     * @mbg.generated
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }
}