package com.yugyg.entity;

import java.util.Date;

public class YgfDljSearchRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygf_dlj_search_record.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygf_dlj_search_record.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygf_dlj_search_record.ip
     *
     * @mbg.generated
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygf_dlj_search_record.browser
     *
     * @mbg.generated
     */
    private String browser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygf_dlj_search_record.equipment
     *
     * @mbg.generated
     */
    private String equipment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygf_dlj_search_record.searchShort
     *
     * @mbg.generated
     */
    private String searchshort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygf_dlj_search_record.ipBelong
     *
     * @mbg.generated
     */
    private String ipbelong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygf_dlj_search_record.resolution
     *
     * @mbg.generated
     */
    private String resolution;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygf_dlj_search_record.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygf_dlj_search_record.cookie
     *
     * @mbg.generated
     */
    private String cookie;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygf_dlj_search_record.referer
     *
     * @mbg.generated
     */
    private String referer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygf_dlj_search_record.userAgent
     *
     * @mbg.generated
     */
    private String useragent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygf_dlj_search_record.phoneNum
     *
     * @mbg.generated
     */
    private String phonenum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygf_dlj_search_record.searchLong
     *
     * @mbg.generated
     */
    private String searchlong;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygf_dlj_search_record.id
     *
     * @return the value of ygf_dlj_search_record.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygf_dlj_search_record.id
     *
     * @param id the value for ygf_dlj_search_record.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygf_dlj_search_record.time
     *
     * @return the value of ygf_dlj_search_record.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygf_dlj_search_record.time
     *
     * @param time the value for ygf_dlj_search_record.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygf_dlj_search_record.ip
     *
     * @return the value of ygf_dlj_search_record.ip
     *
     * @mbg.generated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygf_dlj_search_record.ip
     *
     * @param ip the value for ygf_dlj_search_record.ip
     *
     * @mbg.generated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygf_dlj_search_record.browser
     *
     * @return the value of ygf_dlj_search_record.browser
     *
     * @mbg.generated
     */
    public String getBrowser() {
        return browser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygf_dlj_search_record.browser
     *
     * @param browser the value for ygf_dlj_search_record.browser
     *
     * @mbg.generated
     */
    public void setBrowser(String browser) {
        this.browser = browser == null ? null : browser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygf_dlj_search_record.equipment
     *
     * @return the value of ygf_dlj_search_record.equipment
     *
     * @mbg.generated
     */
    public String getEquipment() {
        return equipment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygf_dlj_search_record.equipment
     *
     * @param equipment the value for ygf_dlj_search_record.equipment
     *
     * @mbg.generated
     */
    public void setEquipment(String equipment) {
        this.equipment = equipment == null ? null : equipment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygf_dlj_search_record.searchShort
     *
     * @return the value of ygf_dlj_search_record.searchShort
     *
     * @mbg.generated
     */
    public String getSearchshort() {
        return searchshort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygf_dlj_search_record.searchShort
     *
     * @param searchshort the value for ygf_dlj_search_record.searchShort
     *
     * @mbg.generated
     */
    public void setSearchshort(String searchshort) {
        this.searchshort = searchshort == null ? null : searchshort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygf_dlj_search_record.ipBelong
     *
     * @return the value of ygf_dlj_search_record.ipBelong
     *
     * @mbg.generated
     */
    public String getIpbelong() {
        return ipbelong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygf_dlj_search_record.ipBelong
     *
     * @param ipbelong the value for ygf_dlj_search_record.ipBelong
     *
     * @mbg.generated
     */
    public void setIpbelong(String ipbelong) {
        this.ipbelong = ipbelong == null ? null : ipbelong.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygf_dlj_search_record.resolution
     *
     * @return the value of ygf_dlj_search_record.resolution
     *
     * @mbg.generated
     */
    public String getResolution() {
        return resolution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygf_dlj_search_record.resolution
     *
     * @param resolution the value for ygf_dlj_search_record.resolution
     *
     * @mbg.generated
     */
    public void setResolution(String resolution) {
        this.resolution = resolution == null ? null : resolution.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygf_dlj_search_record.status
     *
     * @return the value of ygf_dlj_search_record.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygf_dlj_search_record.status
     *
     * @param status the value for ygf_dlj_search_record.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygf_dlj_search_record.cookie
     *
     * @return the value of ygf_dlj_search_record.cookie
     *
     * @mbg.generated
     */
    public String getCookie() {
        return cookie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygf_dlj_search_record.cookie
     *
     * @param cookie the value for ygf_dlj_search_record.cookie
     *
     * @mbg.generated
     */
    public void setCookie(String cookie) {
        this.cookie = cookie == null ? null : cookie.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygf_dlj_search_record.referer
     *
     * @return the value of ygf_dlj_search_record.referer
     *
     * @mbg.generated
     */
    public String getReferer() {
        return referer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygf_dlj_search_record.referer
     *
     * @param referer the value for ygf_dlj_search_record.referer
     *
     * @mbg.generated
     */
    public void setReferer(String referer) {
        this.referer = referer == null ? null : referer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygf_dlj_search_record.userAgent
     *
     * @return the value of ygf_dlj_search_record.userAgent
     *
     * @mbg.generated
     */
    public String getUseragent() {
        return useragent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygf_dlj_search_record.userAgent
     *
     * @param useragent the value for ygf_dlj_search_record.userAgent
     *
     * @mbg.generated
     */
    public void setUseragent(String useragent) {
        this.useragent = useragent == null ? null : useragent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygf_dlj_search_record.phoneNum
     *
     * @return the value of ygf_dlj_search_record.phoneNum
     *
     * @mbg.generated
     */
    public String getPhonenum() {
        return phonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygf_dlj_search_record.phoneNum
     *
     * @param phonenum the value for ygf_dlj_search_record.phoneNum
     *
     * @mbg.generated
     */
    public void setPhonenum(String phonenum) {
        this.phonenum = phonenum == null ? null : phonenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygf_dlj_search_record.searchLong
     *
     * @return the value of ygf_dlj_search_record.searchLong
     *
     * @mbg.generated
     */
    public String getSearchlong() {
        return searchlong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygf_dlj_search_record.searchLong
     *
     * @param searchlong the value for ygf_dlj_search_record.searchLong
     *
     * @mbg.generated
     */
    public void setSearchlong(String searchlong) {
        this.searchlong = searchlong == null ? null : searchlong.trim();
    }
}