package com.yugyg.entity;

public class YgfHours {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygf_hours.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygf_hours.hours
     *
     * @mbg.generated
     */
    private Byte hours;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygf_hours.id
     *
     * @return the value of ygf_hours.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygf_hours.id
     *
     * @param id the value for ygf_hours.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygf_hours.hours
     *
     * @return the value of ygf_hours.hours
     *
     * @mbg.generated
     */
    public Byte getHours() {
        return hours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygf_hours.hours
     *
     * @param hours the value for ygf_hours.hours
     *
     * @mbg.generated
     */
    public void setHours(Byte hours) {
        this.hours = hours;
    }
}