package com.yugyg.entity;

import java.util.Date;

public class YgfLongShortLink {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygf_long_short_link.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygf_long_short_link.shortLink
     *
     * @mbg.generated
     */
    private String shortlink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygf_long_short_link.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygf_long_short_link.desc
     *
     * @mbg.generated
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygf_long_short_link.longLink
     *
     * @mbg.generated
     */
    private String longlink;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygf_long_short_link.id
     *
     * @return the value of ygf_long_short_link.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygf_long_short_link.id
     *
     * @param id the value for ygf_long_short_link.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygf_long_short_link.shortLink
     *
     * @return the value of ygf_long_short_link.shortLink
     *
     * @mbg.generated
     */
    public String getShortlink() {
        return shortlink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygf_long_short_link.shortLink
     *
     * @param shortlink the value for ygf_long_short_link.shortLink
     *
     * @mbg.generated
     */
    public void setShortlink(String shortlink) {
        this.shortlink = shortlink == null ? null : shortlink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygf_long_short_link.time
     *
     * @return the value of ygf_long_short_link.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygf_long_short_link.time
     *
     * @param time the value for ygf_long_short_link.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygf_long_short_link.desc
     *
     * @return the value of ygf_long_short_link.desc
     *
     * @mbg.generated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygf_long_short_link.desc
     *
     * @param desc the value for ygf_long_short_link.desc
     *
     * @mbg.generated
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygf_long_short_link.longLink
     *
     * @return the value of ygf_long_short_link.longLink
     *
     * @mbg.generated
     */
    public String getLonglink() {
        return longlink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygf_long_short_link.longLink
     *
     * @param longlink the value for ygf_long_short_link.longLink
     *
     * @mbg.generated
     */
    public void setLonglink(String longlink) {
        this.longlink = longlink == null ? null : longlink.trim();
    }
}