package com.yugyg.entity;

public class YgfProvince {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygf_province.province_id
     *
     * @mbg.generated
     */
    private Long provinceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygf_province.province_code
     *
     * @mbg.generated
     */
    private String provinceCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygf_province.province_name
     *
     * @mbg.generated
     */
    private String provinceName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygf_province.province_id
     *
     * @return the value of ygf_province.province_id
     *
     * @mbg.generated
     */
    public Long getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygf_province.province_id
     *
     * @param provinceId the value for ygf_province.province_id
     *
     * @mbg.generated
     */
    public void setProvinceId(Long provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygf_province.province_code
     *
     * @return the value of ygf_province.province_code
     *
     * @mbg.generated
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygf_province.province_code
     *
     * @param provinceCode the value for ygf_province.province_code
     *
     * @mbg.generated
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygf_province.province_name
     *
     * @return the value of ygf_province.province_name
     *
     * @mbg.generated
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygf_province.province_name
     *
     * @param provinceName the value for ygf_province.province_name
     *
     * @mbg.generated
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }
}