package com.yugyg.mapper;

import com.yugyg.entity.YgfCity;

public interface YgfCityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ygf_city
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ygf_city
     *
     * @mbg.generated
     */
    int insert(YgfCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ygf_city
     *
     * @mbg.generated
     */
    int insertSelective(YgfCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ygf_city
     *
     * @mbg.generated
     */
    YgfCity selectByPrimaryKey(Long cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ygf_city
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YgfCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ygf_city
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YgfCity record);
}