package com.yugyg.mapper;

import com.yugyg.entity.YgfCalendar;

public interface YgfCalendarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ygf_calendar
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ygf_calendar
     *
     * @mbg.generated
     */
    int insert(YgfCalendar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ygf_calendar
     *
     * @mbg.generated
     */
    int insertSelective(YgfCalendar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ygf_calendar
     *
     * @mbg.generated
     */
    YgfCalendar selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ygf_calendar
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YgfCalendar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ygf_calendar
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YgfCalendar record);
}