package com.yugyg.mapper;

import com.yugyg.entity.YgfDljSearchRecord;

public interface YgfDljSearchRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ygf_dlj_search_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ygf_dlj_search_record
     *
     * @mbg.generated
     */
    int insert(YgfDljSearchRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ygf_dlj_search_record
     *
     * @mbg.generated
     */
    int insertSelective(YgfDljSearchRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ygf_dlj_search_record
     *
     * @mbg.generated
     */
    YgfDljSearchRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ygf_dlj_search_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YgfDljSearchRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ygf_dlj_search_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(YgfDljSearchRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ygf_dlj_search_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YgfDljSearchRecord record);
}