package com.yugyg.mapper;

import com.yugyg.entity.YgfHours;

public interface YgfHoursMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ygf_hours
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ygf_hours
     *
     * @mbg.generated
     */
    int insert(YgfHours record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ygf_hours
     *
     * @mbg.generated
     */
    int insertSelective(YgfHours record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ygf_hours
     *
     * @mbg.generated
     */
    YgfHours selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ygf_hours
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YgfHours record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ygf_hours
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YgfHours record);
}