package com.yugyg.mapper;

import com.yugyg.entity.YgfProvince;

public interface YgfProvinceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ygf_province
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long provinceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ygf_province
     *
     * @mbg.generated
     */
    int insert(YgfProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ygf_province
     *
     * @mbg.generated
     */
    int insertSelective(YgfProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ygf_province
     *
     * @mbg.generated
     */
    YgfProvince selectByPrimaryKey(Long provinceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ygf_province
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YgfProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ygf_province
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YgfProvince record);
}